// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0000_01000_D.proto
// Protobuf Java Version: 4.26.1

package com.lzp.netty.protobuf;

public final class ProtobufTest {
  private ProtobufTest() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      ProtobufTest.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DVector3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:DVector3)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * X坐标
     * </pre>
     *
     * <code>optional float x = 1;</code>
     * @return Whether the x field is set.
     */
    boolean hasX();
    /**
     * <pre>
     * X坐标
     * </pre>
     *
     * <code>optional float x = 1;</code>
     * @return The x.
     */
    float getX();

    /**
     * <pre>
     * Y坐标
     * </pre>
     *
     * <code>optional float y = 2;</code>
     * @return Whether the y field is set.
     */
    boolean hasY();
    /**
     * <pre>
     * Y坐标
     * </pre>
     *
     * <code>optional float y = 2;</code>
     * @return The y.
     */
    float getY();

    /**
     * <pre>
     * Z坐标
     * </pre>
     *
     * <code>optional float z = 3;</code>
     * @return Whether the z field is set.
     */
    boolean hasZ();
    /**
     * <pre>
     * Z坐标
     * </pre>
     *
     * <code>optional float z = 3;</code>
     * @return The z.
     */
    float getZ();
  }
  /**
   * <pre>
   * 3D坐标信息
   * </pre>
   *
   * Protobuf type {@code DVector3}
   */
  public static final class DVector3 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DVector3)
      DVector3OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        DVector3.class.getName());
    }
    // Use DVector3.newBuilder() to construct.
    private DVector3(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DVector3() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufTest.internal_static_DVector3_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufTest.internal_static_DVector3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DVector3.class, Builder.class);
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private float x_ = 0F;
    /**
     * <pre>
     * X坐标
     * </pre>
     *
     * <code>optional float x = 1;</code>
     * @return Whether the x field is set.
     */
    @Override
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * X坐标
     * </pre>
     *
     * <code>optional float x = 1;</code>
     * @return The x.
     */
    @Override
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_ = 0F;
    /**
     * <pre>
     * Y坐标
     * </pre>
     *
     * <code>optional float y = 2;</code>
     * @return Whether the y field is set.
     */
    @Override
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Y坐标
     * </pre>
     *
     * <code>optional float y = 2;</code>
     * @return The y.
     */
    @Override
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_ = 0F;
    /**
     * <pre>
     * Z坐标
     * </pre>
     *
     * <code>optional float z = 3;</code>
     * @return Whether the z field is set.
     */
    @Override
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Z坐标
     * </pre>
     *
     * <code>optional float z = 3;</code>
     * @return The z.
     */
    @Override
    public float getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeFloat(1, x_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(2, y_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(3, z_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DVector3)) {
        return super.equals(obj);
      }
      DVector3 other = (DVector3) obj;

      if (hasX() != other.hasX()) return false;
      if (hasX()) {
        if (Float.floatToIntBits(getX())
            != Float.floatToIntBits(
                other.getX())) return false;
      }
      if (hasY() != other.hasY()) return false;
      if (hasY()) {
        if (Float.floatToIntBits(getY())
            != Float.floatToIntBits(
                other.getY())) return false;
      }
      if (hasZ() != other.hasZ()) return false;
      if (hasZ()) {
        if (Float.floatToIntBits(getZ())
            != Float.floatToIntBits(
                other.getZ())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getX());
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getY());
      }
      if (hasZ()) {
        hash = (37 * hash) + Z_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getZ());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DVector3 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DVector3 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DVector3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DVector3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DVector3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DVector3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DVector3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static DVector3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static DVector3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static DVector3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DVector3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static DVector3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DVector3 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 3D坐标信息
     * </pre>
     *
     * Protobuf type {@code DVector3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DVector3)
        DVector3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufTest.internal_static_DVector3_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufTest.internal_static_DVector3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DVector3.class, Builder.class);
      }

      // Construct using com.lzp.netty.protobuf.ProtobufTest.DVector3.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = 0F;
        y_ = 0F;
        z_ = 0F;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufTest.internal_static_DVector3_descriptor;
      }

      @Override
      public DVector3 getDefaultInstanceForType() {
        return DVector3.getDefaultInstance();
      }

      @Override
      public DVector3 build() {
        DVector3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DVector3 buildPartial() {
        DVector3 result = new DVector3(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(DVector3 result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.z_ = z_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DVector3) {
          return mergeFrom((DVector3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DVector3 other) {
        if (other == DVector3.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                x_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                y_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                z_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float x_ ;
      /**
       * <pre>
       * X坐标
       * </pre>
       *
       * <code>optional float x = 1;</code>
       * @return Whether the x field is set.
       */
      @Override
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * X坐标
       * </pre>
       *
       * <code>optional float x = 1;</code>
       * @return The x.
       */
      @Override
      public float getX() {
        return x_;
      }
      /**
       * <pre>
       * X坐标
       * </pre>
       *
       * <code>optional float x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {

        x_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * X坐标
       * </pre>
       *
       * <code>optional float x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <pre>
       * Y坐标
       * </pre>
       *
       * <code>optional float y = 2;</code>
       * @return Whether the y field is set.
       */
      @Override
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Y坐标
       * </pre>
       *
       * <code>optional float y = 2;</code>
       * @return The y.
       */
      @Override
      public float getY() {
        return y_;
      }
      /**
       * <pre>
       * Y坐标
       * </pre>
       *
       * <code>optional float y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {

        y_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Y坐标
       * </pre>
       *
       * <code>optional float y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <pre>
       * Z坐标
       * </pre>
       *
       * <code>optional float z = 3;</code>
       * @return Whether the z field is set.
       */
      @Override
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Z坐标
       * </pre>
       *
       * <code>optional float z = 3;</code>
       * @return The z.
       */
      @Override
      public float getZ() {
        return z_;
      }
      /**
       * <pre>
       * Z坐标
       * </pre>
       *
       * <code>optional float z = 3;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(float value) {

        z_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Z坐标
       * </pre>
       *
       * <code>optional float z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DVector3)
    }

    // @@protoc_insertion_point(class_scope:DVector3)
    private static final DVector3 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DVector3();
    }

    public static DVector3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DVector3>
        PARSER = new com.google.protobuf.AbstractParser<DVector3>() {
      @Override
      public DVector3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DVector3> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DVector3> getParserForType() {
      return PARSER;
    }

    @Override
    public DVector3 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CSSceneEnterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CSSceneEnter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 当前位置
     * </pre>
     *
     * <code>optional .DVector3 pos = 1;</code>
     * @return Whether the pos field is set.
     */
    boolean hasPos();
    /**
     * <pre>
     * 当前位置
     * </pre>
     *
     * <code>optional .DVector3 pos = 1;</code>
     * @return The pos.
     */
    DVector3 getPos();
    /**
     * <pre>
     * 当前位置
     * </pre>
     *
     * <code>optional .DVector3 pos = 1;</code>
     */
    DVector3OrBuilder getPosOrBuilder();
  }
  /**
   * Protobuf type {@code CSSceneEnter}
   */
  public static final class CSSceneEnter extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CSSceneEnter)
      CSSceneEnterOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        CSSceneEnter.class.getName());
    }
    // Use CSSceneEnter.newBuilder() to construct.
    private CSSceneEnter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CSSceneEnter() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufTest.internal_static_CSSceneEnter_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufTest.internal_static_CSSceneEnter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CSSceneEnter.class, Builder.class);
    }

    private int bitField0_;
    public static final int POS_FIELD_NUMBER = 1;
    private DVector3 pos_;
    /**
     * <pre>
     * 当前位置
     * </pre>
     *
     * <code>optional .DVector3 pos = 1;</code>
     * @return Whether the pos field is set.
     */
    @Override
    public boolean hasPos() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 当前位置
     * </pre>
     *
     * <code>optional .DVector3 pos = 1;</code>
     * @return The pos.
     */
    @Override
    public DVector3 getPos() {
      return pos_ == null ? DVector3.getDefaultInstance() : pos_;
    }
    /**
     * <pre>
     * 当前位置
     * </pre>
     *
     * <code>optional .DVector3 pos = 1;</code>
     */
    @Override
    public DVector3OrBuilder getPosOrBuilder() {
      return pos_ == null ? DVector3.getDefaultInstance() : pos_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getPos());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPos());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CSSceneEnter)) {
        return super.equals(obj);
      }
      CSSceneEnter other = (CSSceneEnter) obj;

      if (hasPos() != other.hasPos()) return false;
      if (hasPos()) {
        if (!getPos()
            .equals(other.getPos())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPos()) {
        hash = (37 * hash) + POS_FIELD_NUMBER;
        hash = (53 * hash) + getPos().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CSSceneEnter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CSSceneEnter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CSSceneEnter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CSSceneEnter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CSSceneEnter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CSSceneEnter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CSSceneEnter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CSSceneEnter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CSSceneEnter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CSSceneEnter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CSSceneEnter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CSSceneEnter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CSSceneEnter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CSSceneEnter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CSSceneEnter)
        CSSceneEnterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufTest.internal_static_CSSceneEnter_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufTest.internal_static_CSSceneEnter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CSSceneEnter.class, Builder.class);
      }

      // Construct using com.lzp.netty.protobuf.ProtobufTest.CSSceneEnter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getPosFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        pos_ = null;
        if (posBuilder_ != null) {
          posBuilder_.dispose();
          posBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufTest.internal_static_CSSceneEnter_descriptor;
      }

      @Override
      public CSSceneEnter getDefaultInstanceForType() {
        return CSSceneEnter.getDefaultInstance();
      }

      @Override
      public CSSceneEnter build() {
        CSSceneEnter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CSSceneEnter buildPartial() {
        CSSceneEnter result = new CSSceneEnter(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CSSceneEnter result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.pos_ = posBuilder_ == null
              ? pos_
              : posBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CSSceneEnter) {
          return mergeFrom((CSSceneEnter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CSSceneEnter other) {
        if (other == CSSceneEnter.getDefaultInstance()) return this;
        if (other.hasPos()) {
          mergePos(other.getPos());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getPosFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private DVector3 pos_;
      private com.google.protobuf.SingleFieldBuilder<
          DVector3, DVector3.Builder, DVector3OrBuilder> posBuilder_;
      /**
       * <pre>
       * 当前位置
       * </pre>
       *
       * <code>optional .DVector3 pos = 1;</code>
       * @return Whether the pos field is set.
       */
      public boolean hasPos() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 当前位置
       * </pre>
       *
       * <code>optional .DVector3 pos = 1;</code>
       * @return The pos.
       */
      public DVector3 getPos() {
        if (posBuilder_ == null) {
          return pos_ == null ? DVector3.getDefaultInstance() : pos_;
        } else {
          return posBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 当前位置
       * </pre>
       *
       * <code>optional .DVector3 pos = 1;</code>
       */
      public Builder setPos(DVector3 value) {
        if (posBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pos_ = value;
        } else {
          posBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前位置
       * </pre>
       *
       * <code>optional .DVector3 pos = 1;</code>
       */
      public Builder setPos(
          DVector3.Builder builderForValue) {
        if (posBuilder_ == null) {
          pos_ = builderForValue.build();
        } else {
          posBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前位置
       * </pre>
       *
       * <code>optional .DVector3 pos = 1;</code>
       */
      public Builder mergePos(DVector3 value) {
        if (posBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            pos_ != null &&
            pos_ != DVector3.getDefaultInstance()) {
            getPosBuilder().mergeFrom(value);
          } else {
            pos_ = value;
          }
        } else {
          posBuilder_.mergeFrom(value);
        }
        if (pos_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * 当前位置
       * </pre>
       *
       * <code>optional .DVector3 pos = 1;</code>
       */
      public Builder clearPos() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pos_ = null;
        if (posBuilder_ != null) {
          posBuilder_.dispose();
          posBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前位置
       * </pre>
       *
       * <code>optional .DVector3 pos = 1;</code>
       */
      public DVector3.Builder getPosBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPosFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 当前位置
       * </pre>
       *
       * <code>optional .DVector3 pos = 1;</code>
       */
      public DVector3OrBuilder getPosOrBuilder() {
        if (posBuilder_ != null) {
          return posBuilder_.getMessageOrBuilder();
        } else {
          return pos_ == null ?
              DVector3.getDefaultInstance() : pos_;
        }
      }
      /**
       * <pre>
       * 当前位置
       * </pre>
       *
       * <code>optional .DVector3 pos = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          DVector3, DVector3.Builder, DVector3OrBuilder>
          getPosFieldBuilder() {
        if (posBuilder_ == null) {
          posBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              DVector3, DVector3.Builder, DVector3OrBuilder>(
                  getPos(),
                  getParentForChildren(),
                  isClean());
          pos_ = null;
        }
        return posBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:CSSceneEnter)
    }

    // @@protoc_insertion_point(class_scope:CSSceneEnter)
    private static final CSSceneEnter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CSSceneEnter();
    }

    public static CSSceneEnter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CSSceneEnter>
        PARSER = new com.google.protobuf.AbstractParser<CSSceneEnter>() {
      @Override
      public CSSceneEnter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CSSceneEnter> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CSSceneEnter> getParserForType() {
      return PARSER;
    }

    @Override
    public CSSceneEnter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SCSceneEnterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SCSceneEnter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 是否进入
     * </pre>
     *
     * <code>required bool enter = 1;</code>
     * @return Whether the enter field is set.
     */
    boolean hasEnter();
    /**
     * <pre>
     * 是否进入
     * </pre>
     *
     * <code>required bool enter = 1;</code>
     * @return The enter.
     */
    boolean getEnter();
  }
  /**
   * Protobuf type {@code SCSceneEnter}
   */
  public static final class SCSceneEnter extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SCSceneEnter)
      SCSceneEnterOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        SCSceneEnter.class.getName());
    }
    // Use SCSceneEnter.newBuilder() to construct.
    private SCSceneEnter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SCSceneEnter() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtobufTest.internal_static_SCSceneEnter_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtobufTest.internal_static_SCSceneEnter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SCSceneEnter.class, Builder.class);
    }

    private int bitField0_;
    public static final int ENTER_FIELD_NUMBER = 1;
    private boolean enter_ = false;
    /**
     * <pre>
     * 是否进入
     * </pre>
     *
     * <code>required bool enter = 1;</code>
     * @return Whether the enter field is set.
     */
    @Override
    public boolean hasEnter() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 是否进入
     * </pre>
     *
     * <code>required bool enter = 1;</code>
     * @return The enter.
     */
    @Override
    public boolean getEnter() {
      return enter_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEnter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, enter_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, enter_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SCSceneEnter)) {
        return super.equals(obj);
      }
      SCSceneEnter other = (SCSceneEnter) obj;

      if (hasEnter() != other.hasEnter()) return false;
      if (hasEnter()) {
        if (getEnter()
            != other.getEnter()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEnter()) {
        hash = (37 * hash) + ENTER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getEnter());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SCSceneEnter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SCSceneEnter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SCSceneEnter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SCSceneEnter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SCSceneEnter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SCSceneEnter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SCSceneEnter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static SCSceneEnter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SCSceneEnter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SCSceneEnter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SCSceneEnter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static SCSceneEnter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SCSceneEnter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SCSceneEnter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SCSceneEnter)
        SCSceneEnterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtobufTest.internal_static_SCSceneEnter_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtobufTest.internal_static_SCSceneEnter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SCSceneEnter.class, Builder.class);
      }

      // Construct using com.lzp.netty.protobuf.ProtobufTest.SCSceneEnter.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        enter_ = false;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtobufTest.internal_static_SCSceneEnter_descriptor;
      }

      @Override
      public SCSceneEnter getDefaultInstanceForType() {
        return SCSceneEnter.getDefaultInstance();
      }

      @Override
      public SCSceneEnter build() {
        SCSceneEnter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SCSceneEnter buildPartial() {
        SCSceneEnter result = new SCSceneEnter(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SCSceneEnter result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.enter_ = enter_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SCSceneEnter) {
          return mergeFrom((SCSceneEnter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SCSceneEnter other) {
        if (other == SCSceneEnter.getDefaultInstance()) return this;
        if (other.hasEnter()) {
          setEnter(other.getEnter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasEnter()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                enter_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean enter_ ;
      /**
       * <pre>
       * 是否进入
       * </pre>
       *
       * <code>required bool enter = 1;</code>
       * @return Whether the enter field is set.
       */
      @Override
      public boolean hasEnter() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 是否进入
       * </pre>
       *
       * <code>required bool enter = 1;</code>
       * @return The enter.
       */
      @Override
      public boolean getEnter() {
        return enter_;
      }
      /**
       * <pre>
       * 是否进入
       * </pre>
       *
       * <code>required bool enter = 1;</code>
       * @param value The enter to set.
       * @return This builder for chaining.
       */
      public Builder setEnter(boolean value) {

        enter_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否进入
       * </pre>
       *
       * <code>required bool enter = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnter() {
        bitField0_ = (bitField0_ & ~0x00000001);
        enter_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SCSceneEnter)
    }

    // @@protoc_insertion_point(class_scope:SCSceneEnter)
    private static final SCSceneEnter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SCSceneEnter();
    }

    public static SCSceneEnter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SCSceneEnter>
        PARSER = new com.google.protobuf.AbstractParser<SCSceneEnter>() {
      @Override
      public SCSceneEnter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SCSceneEnter> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SCSceneEnter> getParserForType() {
      return PARSER;
    }

    @Override
    public SCSceneEnter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DVector3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DVector3_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CSSceneEnter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CSSceneEnter_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SCSceneEnter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SCSceneEnter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\0220000_01000_D.proto\032\roptions.proto\"+\n\010D" +
      "Vector3\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002" +
      "\",\n\014CSSceneEnter\022\026\n\003pos\030\001 \001(\0132\t.DVector3" +
      ":\004\210\361\004\t\"#\n\014SCSceneEnter\022\r\n\005enter\030\001 \002(\010:\004\210" +
      "\361\004\nB&\n\026com.lzp.netty.protobufB\014ProtobufT" +
      "est"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Options.getDescriptor(),
        });
    internal_static_DVector3_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DVector3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DVector3_descriptor,
        new String[] { "X", "Y", "Z", });
    internal_static_CSSceneEnter_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CSSceneEnter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CSSceneEnter_descriptor,
        new String[] { "Pos", });
    internal_static_SCSceneEnter_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SCSceneEnter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SCSceneEnter_descriptor,
        new String[] { "Enter", });
    descriptor.resolveAllFeaturesImmutable();
    Options.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(Options.msgid);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
